### ISSUE TITLE
Will this be able to use in Microsoft Edge(Chromium kernel) in the future?

### ISSUE THREAD

**Issue by chengziorange** [doki-theme/doki-theme-chrome#1]
Currently it doesn't take effect in Edge, I like this project and I wonder whethere I can use it in Edge.

**Comment by Unthrottled** [comment]
Hey!

I tried to import it into Edge a while back, however, the background image did not apply, which is like the main feature I want.

I can look into seeing if it is possible to set the background image in Edge. Thanks for the interest :smile:

**Comment by Unthrottled** [comment]
@chengziorange 

After some digging, I found a work around to make Edge take effect.

![Annotation 2020-07-10 183142](https://user-images.githubusercontent.com/15972415/87211113-97e2b700-c2dd-11ea-826c-2d1d8448f412.png)

[Here are the instructions](https://github.com/doki-theme/doki-theme-chrome#microsoft-edge-1). Let me know if you need any help.

Thanks for the suggestion! 🎉
