### ISSUE TITLE
Konata Theme

### ISSUE THREAD

**Issue by ZimCodes** [doki-theme/doki-theme-chrome#16]
**Describe the bug**

Konata's theme is very bright, of course, since it is a light theme. 

The colors for the _toolbar_field_ & _toolbar_field_text_ blend too well together. It is difficult to see the text in the address bar very well while both in focus and out of focus. 

A solution I recommend is changing the toolbar to  [these settings instead](https://github.com/doki-theme/doki-theme-chrome/commit/5fb95b55e3a9d757a92332ec352a64cc00b0ed50#diff-328150276c96be0aa5c2f412484424988c6ddfa883fb1c132b6dd30ace61d0b2)

**To Reproduce**

1.Load the extension
1.Select Konata
1.Stress your eyes

**Expected Behavior**

I am expected to have a nice browsing experience, with a great theme featuring an anime character.
**Environment**

**Screenshots**

# Before
![Screenshot (51)](https://user-images.githubusercontent.com/23222943/102948452-f97a9480-44bd-11eb-8c90-4b5de8bd8c1e.png)
# After
![Screenshot (48)](https://user-images.githubusercontent.com/23222943/102948460-fb445800-44bd-11eb-897a-316e2820b147.png)

**Comment by Unthrottled** [comment]
:thinking: 

So as part of my work with the new themes, I was also planning on re-imagining Konata's theme.

It should make the theme a bit easier to maintain and more usable. The platforms aren't really built for this type of vivid theme :sweat_smile:

**Comment by Unthrottled** [comment]
Alright this is what the new Konata looks like

![Screenshot from 2020-12-31 09-05-48](https://user-images.githubusercontent.com/15972415/103415399-8a4d1200-4b47-11eb-9306-d559f1fde8a9.png)

I think it's usable now :+1:
